/* Generated by Yosys 0.9+4288 (git sha1 b2e97174, x86_64-conda_cos6-linux-gnu-gcc 1.24.0.133_b0863d8_dirty -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1630451134687/work=/usr/local/src/conda/yosys-0.9_5586_gb2e97174 -fdebug-prefix-map=/home/carlos/miniconda3/envs/fpga=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

/* top =  1  */
/* src = "mult_32.v:1.1-27.10" */
module mult_32(clk, rst, init, A, B, pp, done);
  /* src = "mult_32.v:6.16-6.17" */
  input [15:0] A;
  /* src = "mult_32.v:7.16-7.17" */
  input [15:0] B;
  /* hdlname = "acc0 A" */
  /* src = "mult_32.v:23.7-23.70|acc.v:3.16-3.17" */
  wire [31:0] \acc0.A ;
  /* hdlname = "acc0 add" */
  /* src = "mult_32.v:23.7-23.70|acc.v:4.9-4.12" */
  wire \acc0.add ;
  /* hdlname = "acc0 clk" */
  /* src = "mult_32.v:23.7-23.70|acc.v:2.9-2.12" */
  wire \acc0.clk ;
  /* hdlname = "acc0 pp" */
  /* src = "mult_32.v:23.7-23.70|acc.v:6.21-6.23" */
  wire [31:0] \acc0.pp ;
  /* force_downto = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" */
  wire [31:0] \acc0.pp_SB_CARRY_I1_CO ;
  /* force_downto = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:33.26-33.27" */
  wire [31:0] \acc0.pp_SB_DFFNESR_Q_D ;
  /* hdlname = "acc0 rst" */
  /* src = "mult_32.v:23.7-23.70|acc.v:5.9-5.12" */
  wire \acc0.rst ;
  /* src = "mult_32.v:4.9-4.12" */
  input clk;
  /* hdlname = "comp0 B" */
  /* src = "mult_32.v:22.8-22.31|comp.v:2.15-2.16" */
  wire [15:0] \comp0.B ;
  /* hdlname = "control0 add" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:13.13-13.16" */
  wire \control0.add ;
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4" */
  wire \control0.add_SB_DFFE_Q_D ;
  wire \control0.add_SB_LUT4_I3_O ;
  /* hdlname = "control0 clk" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:4.8-4.11" */
  wire \control0.clk ;
  /* hdlname = "control0 count" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:32.11-32.16" */
  wire [3:0] \control0.count ;
  /* force_downto = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:84.17-84.26|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" */
  wire [3:0] \control0.count_SB_CARRY_CI_CO ;
  /* force_downto = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:84.17-84.26|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:33.26-33.27" */
  wire [3:0] \control0.count_SB_DFFESR_Q_D ;
  /* hdlname = "control0 done" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:10.13-10.17" */
  wire \control0.done ;
  /* force_downto = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:38.5-89.11|control_mult.v:0.0-0.0|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:573.22-573.23" */
  /* unused_bits = "1 2 3 4" */
  wire [4:0] \control0.done_SB_DFFE_Q_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [2:0] \control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O ;
  wire \control0.done_SB_DFFE_Q_D_SB_LUT4_I3_O ;
  /* hdlname = "control0 init" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:7.8-7.12" */
  wire \control0.init ;
  /* hdlname = "control0 lsb_B" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:6.8-6.13" */
  wire \control0.lsb_B ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \control0.lsb_B_SB_DFFNE_Q_D ;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [3:0] \control0.lsb_B_SB_LUT4_I0_O ;
  /* hdlname = "control0 reset" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:12.13-12.18" */
  wire \control0.reset ;
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4" */
  wire \control0.reset_SB_DFFE_Q_D ;
  /* hdlname = "control0 rst" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:5.8-5.11" */
  wire \control0.rst ;
  /* hdlname = "control0 sh" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:11.13-11.15" */
  wire \control0.sh ;
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4" */
  wire \control0.sh_SB_DFFE_Q_D ;
  wire \control0.sh_SB_LUT4_I2_O ;
  /* hdlname = "control0 state" */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:22.12-22.17" */
  wire [2:0] \control0.state ;
  wire \control0.state_SB_DFFSR_Q_R ;
  /* src = "mult_32.v:9.10-9.14" */
  output done;
  /* src = "mult_32.v:5.9-5.13" */
  input init;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [2:0] init_SB_LUT4_I1_O;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [2:0] init_SB_LUT4_I1_O_SB_LUT4_I1_O;
  /* force_downto = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:38.5-89.11|control_mult.v:0.0-0.0|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:578.19-578.22" */
  wire [2:0] init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O;
  /* hdlname = "lsr0 clk" */
  /* src = "mult_32.v:21.7-21.77|lsr.v:2.9-2.12" */
  wire \lsr0.clk ;
  /* hdlname = "lsr0 in_A" */
  /* src = "mult_32.v:21.7-21.77|lsr.v:3.15-3.19" */
  wire [15:0] \lsr0.in_A ;
  /* hdlname = "lsr0 load" */
  /* src = "mult_32.v:21.7-21.77|lsr.v:4.9-4.13" */
  wire \lsr0.load ;
  /* hdlname = "lsr0 s_A" */
  /* src = "mult_32.v:21.7-21.77|lsr.v:6.20-6.23" */
  wire [30:0] \lsr0.s_A ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_10_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_11_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_12_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_13_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_14_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_1_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_2_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_3_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_4_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_5_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_6_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_7_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_8_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_9_D ;
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7" */
  wire \lsr0.s_A_SB_DFFNE_Q_D ;
  /* hdlname = "lsr0 shift" */
  /* src = "mult_32.v:21.7-21.77|lsr.v:5.9-5.14" */
  wire \lsr0.shift ;
  /* src = "mult_32.v:8.17-8.19" */
  output [31:0] pp;
  /* hdlname = "rsr0 clk" */
  /* src = "mult_32.v:20.7-20.77|rsr.v:2.9-2.12" */
  wire \rsr0.clk ;
  /* hdlname = "rsr0 in_B" */
  /* src = "mult_32.v:20.7-20.77|rsr.v:3.15-3.19" */
  wire [15:0] \rsr0.in_B ;
  /* hdlname = "rsr0 load" */
  /* src = "mult_32.v:20.7-20.77|rsr.v:4.9-4.13" */
  wire \rsr0.load ;
  /* hdlname = "rsr0 s_B" */
  /* src = "mult_32.v:20.7-20.77|rsr.v:6.20-6.23" */
  wire [15:0] \rsr0.s_B ;
  wire \rsr0.s_B_SB_DFFNESR_Q_R ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_10_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_11_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_12_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_13_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_1_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_2_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_3_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_4_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_5_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_6_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_7_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_8_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_9_D ;
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7" */
  wire \rsr0.s_B_SB_DFFNE_Q_D ;
  /* hdlname = "rsr0 shift" */
  /* src = "mult_32.v:20.7-20.77|rsr.v:5.9-5.14" */
  wire \rsr0.shift ;
  /* src = "mult_32.v:3.9-3.12" */
  input rst;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire rst_SB_LUT4_I2_O;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [2:0] rst_SB_LUT4_I3_O;
  /* src = "mult_32.v:16.15-16.18" */
  wire [31:0] w_A;
  /* src = "mult_32.v:17.15-17.18" */
  wire [15:0] w_B;
  /* src = "mult_32.v:13.8-13.13" */
  wire w_add;
  /* src = "mult_32.v:12.8-12.15" */
  wire w_reset;
  /* src = "mult_32.v:11.8-11.12" */
  wire w_sh;
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [9]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [10]),
    .I0(\lsr0.s_A [9]),
    .I1(\acc0.pp [9])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_1  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [8]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [9]),
    .I0(\lsr0.s_A [8]),
    .I1(\acc0.pp [8])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_10  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [28]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [29]),
    .I0(\lsr0.s_A [28]),
    .I1(\acc0.pp [28])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_11  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [27]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [28]),
    .I0(\lsr0.s_A [27]),
    .I1(\acc0.pp [27])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_12  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [26]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [27]),
    .I0(\lsr0.s_A [26]),
    .I1(\acc0.pp [26])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_13  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [25]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [26]),
    .I0(\lsr0.s_A [25]),
    .I1(\acc0.pp [25])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_14  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [24]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [25]),
    .I0(\lsr0.s_A [24]),
    .I1(\acc0.pp [24])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_15  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [23]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [24]),
    .I0(\lsr0.s_A [23]),
    .I1(\acc0.pp [23])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_16  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [22]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [23]),
    .I0(\lsr0.s_A [22]),
    .I1(\acc0.pp [22])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_17  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [21]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [22]),
    .I0(\lsr0.s_A [21]),
    .I1(\acc0.pp [21])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_18  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [20]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [21]),
    .I0(\lsr0.s_A [20]),
    .I1(\acc0.pp [20])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_19  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [1]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [2]),
    .I0(\lsr0.s_A [1]),
    .I1(\acc0.pp [1])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_2  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [7]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [8]),
    .I0(\lsr0.s_A [7]),
    .I1(\acc0.pp [7])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_20  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [19]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [20]),
    .I0(\lsr0.s_A [19]),
    .I1(\acc0.pp [19])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_21  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [18]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [19]),
    .I0(\lsr0.s_A [18]),
    .I1(\acc0.pp [18])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_22  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [17]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [18]),
    .I0(\lsr0.s_A [17]),
    .I1(\acc0.pp [17])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_23  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [16]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [17]),
    .I0(\lsr0.s_A [16]),
    .I1(\acc0.pp [16])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_24  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [15]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [16]),
    .I0(\lsr0.s_A [15]),
    .I1(\acc0.pp [15])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_25  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [14]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [15]),
    .I0(\lsr0.s_A [14]),
    .I1(\acc0.pp [14])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_26  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [13]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [14]),
    .I0(\lsr0.s_A [13]),
    .I1(\acc0.pp [13])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_27  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [12]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [13]),
    .I0(\lsr0.s_A [12]),
    .I1(\acc0.pp [12])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_28  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [11]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [12]),
    .I0(\lsr0.s_A [11]),
    .I1(\acc0.pp [11])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_29  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [10]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [11]),
    .I0(\lsr0.s_A [10]),
    .I1(\acc0.pp [10])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_3  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [6]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [7]),
    .I0(\lsr0.s_A [6]),
    .I1(\acc0.pp [6])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_30  (
    .CI(1'h0),
    .CO(\acc0.pp_SB_CARRY_I1_CO [1]),
    .I0(\lsr0.s_A [0]),
    .I1(\acc0.pp [0])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_4  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [5]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [6]),
    .I0(\lsr0.s_A [5]),
    .I1(\acc0.pp [5])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_5  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [4]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [5]),
    .I0(\lsr0.s_A [4]),
    .I1(\acc0.pp [4])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_6  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [3]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [4]),
    .I0(\lsr0.s_A [3]),
    .I1(\acc0.pp [3])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_7  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [30]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [31]),
    .I0(\lsr0.s_A [30]),
    .I1(\acc0.pp [30])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_8  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [2]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [3]),
    .I0(\lsr0.s_A [2]),
    .I1(\acc0.pp [2])
  );
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \acc0.pp_SB_CARRY_I1_9  (
    .CI(\acc0.pp_SB_CARRY_I1_CO [29]),
    .CO(\acc0.pp_SB_CARRY_I1_CO [30]),
    .I0(\lsr0.s_A [29]),
    .I1(\acc0.pp [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [31]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [31]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_1  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [30]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [30]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_10  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [21]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [21]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_11  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [20]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [20]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_12  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [19]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [19]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_13  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [18]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [18]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_14  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [17]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [17]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_15  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [16]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [16]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_16  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [15]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [15]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_17  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [14]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [14]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_18  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [13]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [13]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_19  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [12]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [12]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_2  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [29]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [29]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_20  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [11]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [11]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_21  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [10]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [10]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_22  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [9]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [9]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_23  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [8]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [8]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_24  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [7]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [7]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_25  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [6]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [6]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_26  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [5]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [5]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_27  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [4]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [4]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_28  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [3]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [3]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_29  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [2]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [2]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_3  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [28]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [28]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_30  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [1]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [1]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_31  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [0]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [0]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_4  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [27]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [27]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_5  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [26]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [26]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_6  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [25]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [25]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_7  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [24]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [24]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_8  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [23]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [23]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:10.1-17.9|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \acc0.pp_SB_DFFNESR_Q_9  (
    .C(clk),
    .D(\acc0.pp_SB_DFFNESR_Q_D [22]),
    .E(\control0.add_SB_LUT4_I3_O ),
    .Q(\acc0.pp [22]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2  (
    .I0(1'h0),
    .I1(\lsr0.s_A [8]),
    .I2(\acc0.pp [8]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [8]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_1  (
    .I0(1'h0),
    .I1(\lsr0.s_A [7]),
    .I2(\acc0.pp [7]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [7]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_10  (
    .I0(1'h0),
    .I1(\lsr0.s_A [28]),
    .I2(\acc0.pp [28]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [28]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_11  (
    .I0(1'h0),
    .I1(\lsr0.s_A [27]),
    .I2(\acc0.pp [27]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [27]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_12  (
    .I0(1'h0),
    .I1(\lsr0.s_A [26]),
    .I2(\acc0.pp [26]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [26]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_13  (
    .I0(1'h0),
    .I1(\lsr0.s_A [25]),
    .I2(\acc0.pp [25]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [25]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_14  (
    .I0(1'h0),
    .I1(\lsr0.s_A [24]),
    .I2(\acc0.pp [24]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [24]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_15  (
    .I0(1'h0),
    .I1(\lsr0.s_A [23]),
    .I2(\acc0.pp [23]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [23]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_16  (
    .I0(1'h0),
    .I1(\lsr0.s_A [22]),
    .I2(\acc0.pp [22]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [22]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_17  (
    .I0(1'h0),
    .I1(\lsr0.s_A [21]),
    .I2(\acc0.pp [21]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [21]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_18  (
    .I0(1'h0),
    .I1(\lsr0.s_A [20]),
    .I2(\acc0.pp [20]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [20]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_19  (
    .I0(1'h0),
    .I1(\lsr0.s_A [1]),
    .I2(\acc0.pp [1]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [1]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_2  (
    .I0(1'h0),
    .I1(\lsr0.s_A [6]),
    .I2(\acc0.pp [6]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [6]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_20  (
    .I0(1'h0),
    .I1(\lsr0.s_A [19]),
    .I2(\acc0.pp [19]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [19]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_21  (
    .I0(1'h0),
    .I1(\lsr0.s_A [18]),
    .I2(\acc0.pp [18]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [18]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_22  (
    .I0(1'h0),
    .I1(\lsr0.s_A [17]),
    .I2(\acc0.pp [17]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [17]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_23  (
    .I0(1'h0),
    .I1(\lsr0.s_A [16]),
    .I2(\acc0.pp [16]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [16]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_24  (
    .I0(1'h0),
    .I1(\lsr0.s_A [15]),
    .I2(\acc0.pp [15]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [15]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_25  (
    .I0(1'h0),
    .I1(\lsr0.s_A [14]),
    .I2(\acc0.pp [14]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [14]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_26  (
    .I0(1'h0),
    .I1(\lsr0.s_A [13]),
    .I2(\acc0.pp [13]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [13]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_27  (
    .I0(1'h0),
    .I1(\lsr0.s_A [12]),
    .I2(\acc0.pp [12]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [12]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_28  (
    .I0(1'h0),
    .I1(\lsr0.s_A [11]),
    .I2(\acc0.pp [11]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [11]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_29  (
    .I0(1'h0),
    .I1(\lsr0.s_A [10]),
    .I2(\acc0.pp [10]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [10]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_3  (
    .I0(1'h0),
    .I1(\lsr0.s_A [5]),
    .I2(\acc0.pp [5]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [5]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_30  (
    .I0(1'h0),
    .I1(\lsr0.s_A [0]),
    .I2(\acc0.pp [0]),
    .I3(1'h0),
    .O(\acc0.pp_SB_DFFNESR_Q_D [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_31  (
    .I0(1'h0),
    .I1(\lsr0.s_A [9]),
    .I2(\acc0.pp [9]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [9]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_4  (
    .I0(1'h0),
    .I1(\lsr0.s_A [4]),
    .I2(\acc0.pp [4]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [4]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_5  (
    .I0(1'h0),
    .I1(\lsr0.s_A [3]),
    .I2(\acc0.pp [3]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [3]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_6  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\acc0.pp [31]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [31]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_7  (
    .I0(1'h0),
    .I1(\lsr0.s_A [30]),
    .I2(\acc0.pp [30]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [30]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_8  (
    .I0(1'h0),
    .I1(\lsr0.s_A [2]),
    .I2(\acc0.pp [2]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [2]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:23.7-23.70|acc.v:15.21-15.27|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \acc0.pp_SB_LUT4_I2_9  (
    .I0(1'h0),
    .I1(\lsr0.s_A [29]),
    .I2(\acc0.pp [29]),
    .I3(\acc0.pp_SB_CARRY_I1_CO [29]),
    .O(\acc0.pp_SB_DFFNESR_Q_D [29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:5.57-5.103" */
  SB_DFFE \control0.add_SB_DFFE_Q  (
    .C(clk),
    .D(\control0.add_SB_DFFE_Q_D ),
    .E(rst_SB_LUT4_I2_O),
    .Q(\control0.add )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hfcc0)
  ) \control0.add_SB_DFFE_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\control0.state [2]),
    .I2(\control0.state [0]),
    .I3(\control0.state [1]),
    .O(\control0.add_SB_DFFE_Q_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hfff0)
  ) \control0.add_SB_LUT4_I3  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.reset ),
    .I3(\control0.add ),
    .O(\control0.add_SB_LUT4_I3_O )
  );
  /* src = "mult_32.v:24.16-24.147|control_mult.v:84.17-84.26|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \control0.count_SB_CARRY_CI  (
    .CI(\control0.count [0]),
    .CO(\control0.count_SB_CARRY_CI_CO [2]),
    .I0(1'h0),
    .I1(\control0.count [1])
  );
  /* src = "mult_32.v:24.16-24.147|control_mult.v:84.17-84.26|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY \control0.count_SB_CARRY_I1  (
    .CI(\control0.count_SB_CARRY_CI_CO [2]),
    .CO(\control0.count_SB_CARRY_CI_CO [3]),
    .I0(1'h0),
    .I1(\control0.count [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:24.66-24.119" */
  SB_DFFESR \control0.count_SB_DFFESR_Q  (
    .C(clk),
    .D(\control0.count_SB_DFFESR_Q_D [3]),
    .E(rst_SB_LUT4_I3_O[2]),
    .Q(\control0.count [3]),
    .R(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_O )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:24.66-24.119" */
  SB_DFFESR \control0.count_SB_DFFESR_Q_1  (
    .C(clk),
    .D(\control0.count_SB_DFFESR_Q_D [2]),
    .E(rst_SB_LUT4_I3_O[2]),
    .Q(\control0.count [2]),
    .R(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_O )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:24.66-24.119" */
  SB_DFFESR \control0.count_SB_DFFESR_Q_2  (
    .C(clk),
    .D(\control0.count_SB_DFFESR_Q_D [1]),
    .E(rst_SB_LUT4_I3_O[2]),
    .Q(\control0.count [1]),
    .R(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_O )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:24.66-24.119" */
  SB_DFFESR \control0.count_SB_DFFESR_Q_3  (
    .C(clk),
    .D(\control0.count_SB_DFFESR_Q_D [0]),
    .E(rst_SB_LUT4_I3_O[2]),
    .Q(\control0.count [0]),
    .R(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_O )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:84.17-84.26|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \control0.count_SB_LUT4_I2  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.count [3]),
    .I3(\control0.count_SB_CARRY_CI_CO [3]),
    .O(\control0.count_SB_DFFESR_Q_D [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:84.17-84.26|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \control0.count_SB_LUT4_I2_1  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.count [2]),
    .I3(\control0.count_SB_CARRY_CI_CO [2]),
    .O(\control0.count_SB_DFFESR_Q_D [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:84.17-84.26|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) \control0.count_SB_LUT4_I2_2  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.count [1]),
    .I3(\control0.count [0]),
    .O(\control0.count_SB_DFFESR_Q_D [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \control0.count_SB_LUT4_I3  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(\control0.count [0]),
    .O(\control0.count_SB_DFFESR_Q_D [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:5.57-5.103" */
  SB_DFFE \control0.done_SB_DFFE_Q  (
    .C(clk),
    .D(\control0.done_SB_DFFE_Q_D [0]),
    .E(rst_SB_LUT4_I2_O),
    .Q(\control0.done )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \control0.done_SB_DFFE_Q_D_SB_LUT4_I3  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(\control0.done_SB_DFFE_Q_D [0]),
    .O(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_O )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h1f00)
  ) \control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1  (
    .I0(\control0.count_SB_DFFESR_Q_D [1]),
    .I1(\control0.count_SB_DFFESR_Q_D [2]),
    .I2(\control0.count_SB_DFFESR_Q_D [3]),
    .I3(\control0.done_SB_DFFE_Q_D [0]),
    .O(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) \control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\control0.state [2]),
    .I2(\control0.state [0]),
    .I3(\control0.state [1]),
    .O(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) \control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O_SB_LUT4_O_1  (
    .I0(\control0.lsb_B_SB_LUT4_I0_O [0]),
    .I1(\control0.lsb_B_SB_LUT4_I0_O [1]),
    .I2(\control0.lsb_B_SB_LUT4_I0_O [2]),
    .I3(\control0.lsb_B_SB_LUT4_I0_O [3]),
    .O(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) \control0.done_SB_DFFE_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\control0.state [0]),
    .I2(\control0.state [1]),
    .I3(\control0.state [2]),
    .O(\control0.done_SB_DFFE_Q_D [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \control0.lsb_B_SB_DFFNE_Q  (
    .C(clk),
    .D(\control0.lsb_B_SB_DFFNE_Q_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\control0.lsb_B )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \control0.lsb_B_SB_DFFNE_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [1]),
    .I2(B[0]),
    .I3(\control0.reset ),
    .O(\control0.lsb_B_SB_DFFNE_Q_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0001)
  ) \control0.lsb_B_SB_LUT4_I0  (
    .I0(\control0.lsb_B ),
    .I1(\rsr0.s_B [1]),
    .I2(\rsr0.s_B [2]),
    .I3(\rsr0.s_B [3]),
    .O(\control0.lsb_B_SB_LUT4_I0_O [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0001)
  ) \control0.lsb_B_SB_LUT4_I0_O_SB_LUT4_O  (
    .I0(\rsr0.s_B [12]),
    .I1(\rsr0.s_B [13]),
    .I2(\rsr0.s_B [14]),
    .I3(\rsr0.s_B [15]),
    .O(\control0.lsb_B_SB_LUT4_I0_O [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0001)
  ) \control0.lsb_B_SB_LUT4_I0_O_SB_LUT4_O_1  (
    .I0(\rsr0.s_B [8]),
    .I1(\rsr0.s_B [9]),
    .I2(\rsr0.s_B [10]),
    .I3(\rsr0.s_B [11]),
    .O(\control0.lsb_B_SB_LUT4_I0_O [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0001)
  ) \control0.lsb_B_SB_LUT4_I0_O_SB_LUT4_O_2  (
    .I0(\rsr0.s_B [4]),
    .I1(\rsr0.s_B [5]),
    .I2(\rsr0.s_B [6]),
    .I3(\rsr0.s_B [7]),
    .O(\control0.lsb_B_SB_LUT4_I0_O [0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:5.57-5.103" */
  SB_DFFE \control0.reset_SB_DFFE_Q  (
    .C(clk),
    .D(\control0.reset_SB_DFFE_Q_D ),
    .E(rst_SB_LUT4_I2_O),
    .Q(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hfc03)
  ) \control0.reset_SB_DFFE_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\control0.state [0]),
    .I2(\control0.state [1]),
    .I3(\control0.state [2]),
    .O(\control0.reset_SB_DFFE_Q_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:5.57-5.103" */
  SB_DFFE \control0.sh_SB_DFFE_Q  (
    .C(clk),
    .D(\control0.sh_SB_DFFE_Q_D ),
    .E(rst_SB_LUT4_I2_O),
    .Q(\control0.sh )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \control0.sh_SB_DFFE_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\control0.state [1]),
    .I2(\control0.state [2]),
    .I3(\control0.state [0]),
    .O(\control0.sh_SB_DFFE_Q_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hfff0)
  ) \control0.sh_SB_LUT4_I2  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.sh ),
    .I3(\control0.reset ),
    .O(\control0.sh_SB_LUT4_I2_O )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" */
  SB_DFFSR \control0.state_SB_DFFSR_Q  (
    .C(clk),
    .D(init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O[0]),
    .Q(\control0.state [0]),
    .R(\control0.state_SB_DFFSR_Q_R )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" */
  SB_DFFSR \control0.state_SB_DFFSR_Q_1  (
    .C(clk),
    .D(init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O[1]),
    .Q(\control0.state [1]),
    .R(\control0.state_SB_DFFSR_Q_R )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:24.16-24.147|control_mult.v:34.1-91.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:19.59-19.105" */
  SB_DFFSR \control0.state_SB_DFFSR_Q_2  (
    .C(clk),
    .D(init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O[2]),
    .Q(\control0.state [2]),
    .R(\control0.state_SB_DFFSR_Q_R )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \control0.state_SB_DFFSR_Q_R_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(rst_SB_LUT4_I2_O),
    .O(\control0.state_SB_DFFSR_Q_R )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0f33)
  ) init_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(init),
    .I2(\control0.lsb_B ),
    .I3(\control0.state [0]),
    .O(init_SB_LUT4_I1_O[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0003)
  ) init_SB_LUT4_I1_O_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(init_SB_LUT4_I1_O[0]),
    .I2(\control0.state [2]),
    .I3(\control0.state [1]),
    .O(init_SB_LUT4_I1_O_SB_LUT4_I1_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hff30)
  ) init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [0]),
    .I2(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [1]),
    .I3(init_SB_LUT4_I1_O_SB_LUT4_I1_O[2]),
    .O(init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(\control0.state [2]),
    .I3(\control0.state [0]),
    .O(init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hffc0)
  ) init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [0]),
    .I2(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [1]),
    .I3(\control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [2]),
    .O(init_SB_LUT4_I1_O_SB_LUT4_I1_O_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q  (
    .C(clk),
    .D(\lsr0.s_A [29]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [30]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_1  (
    .C(clk),
    .D(\lsr0.s_A [28]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [29]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_10  (
    .C(clk),
    .D(\lsr0.s_A [19]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [20]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_11  (
    .C(clk),
    .D(\lsr0.s_A [18]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [19]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_12  (
    .C(clk),
    .D(\lsr0.s_A [17]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [18]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_13  (
    .C(clk),
    .D(\lsr0.s_A [16]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [17]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_14  (
    .C(clk),
    .D(\lsr0.s_A [15]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [16]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_15  (
    .C(clk),
    .D(A[0]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [0]),
    .R(\rsr0.s_B_SB_DFFNESR_Q_R )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_2  (
    .C(clk),
    .D(\lsr0.s_A [27]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [28]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_3  (
    .C(clk),
    .D(\lsr0.s_A [26]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [27]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_4  (
    .C(clk),
    .D(\lsr0.s_A [25]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [26]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_5  (
    .C(clk),
    .D(\lsr0.s_A [24]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [25]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_6  (
    .C(clk),
    .D(\lsr0.s_A [23]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [24]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_7  (
    .C(clk),
    .D(\lsr0.s_A [22]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [23]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_8  (
    .C(clk),
    .D(\lsr0.s_A [21]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [22]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \lsr0.s_A_SB_DFFNESR_Q_9  (
    .C(clk),
    .D(\lsr0.s_A [20]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [21]),
    .R(\control0.reset )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_1  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_1_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_10  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_10_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_10_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [4]),
    .I2(A[5]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_10_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_11  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_11_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_11_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [3]),
    .I2(A[4]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_11_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_12  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_12_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_12_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [2]),
    .I2(A[3]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_12_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_13  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_13_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_13_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [1]),
    .I2(A[2]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_13_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_14  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_14_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_14_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [0]),
    .I2(A[1]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_14_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_1_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [13]),
    .I2(A[14]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_1_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_2  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_2_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_2_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [12]),
    .I2(A[13]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_2_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_3  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_3_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_3_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [11]),
    .I2(A[12]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_3_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_4  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_4_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_4_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [10]),
    .I2(A[11]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_4_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_5  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_5_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_5_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [9]),
    .I2(A[10]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_5_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_6  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_6_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_6_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [8]),
    .I2(A[9]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_6_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_7  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_7_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_7_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [7]),
    .I2(A[8]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_7_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_8  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_8_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_8_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [6]),
    .I2(A[7]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_8_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:21.7-21.77|lsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \lsr0.s_A_SB_DFFNE_Q_9  (
    .C(clk),
    .D(\lsr0.s_A_SB_DFFNE_Q_9_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\lsr0.s_A [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_9_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [5]),
    .I2(A[6]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_9_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \lsr0.s_A_SB_DFFNE_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\lsr0.s_A [14]),
    .I2(A[15]),
    .I3(\control0.reset ),
    .O(\lsr0.s_A_SB_DFFNE_Q_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR \rsr0.s_B_SB_DFFNESR_Q  (
    .C(clk),
    .D(B[15]),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [15]),
    .R(\rsr0.s_B_SB_DFFNESR_Q_R )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) \rsr0.s_B_SB_DFFNESR_Q_R_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNESR_Q_R )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_1  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_1_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_10  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_10_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_10_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [5]),
    .I2(B[4]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_10_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_11  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_11_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_11_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [4]),
    .I2(B[3]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_11_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_12  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_12_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_12_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [3]),
    .I2(B[2]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_12_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_13  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_13_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_13_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [2]),
    .I2(B[1]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_13_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_1_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [14]),
    .I2(B[13]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_1_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_2  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_2_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_2_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [13]),
    .I2(B[12]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_2_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_3  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_3_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_3_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [12]),
    .I2(B[11]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_3_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_4  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_4_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_4_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [11]),
    .I2(B[10]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_4_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_5  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_5_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_5_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [10]),
    .I2(B[9]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_5_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_6  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_6_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_6_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [9]),
    .I2(B[8]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_6_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_7  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_7_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_7_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [8]),
    .I2(B[7]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_7_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_8  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_8_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_8_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [7]),
    .I2(B[6]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_8_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "mult_32.v:20.7-20.77|rsr.v:8.1-15.7|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE \rsr0.s_B_SB_DFFNE_Q_9  (
    .C(clk),
    .D(\rsr0.s_B_SB_DFFNE_Q_9_D ),
    .E(\control0.sh_SB_LUT4_I2_O ),
    .Q(\rsr0.s_B [5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_9_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [6]),
    .I2(B[5]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_9_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) \rsr0.s_B_SB_DFFNE_Q_D_SB_LUT4_O  (
    .I0(1'h0),
    .I1(\rsr0.s_B [15]),
    .I2(B[14]),
    .I3(\control0.reset ),
    .O(\rsr0.s_B_SB_DFFNE_Q_D )
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hff03)
  ) rst_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(\control0.state [2]),
    .I2(rst),
    .I3(rst_SB_LUT4_I3_O[2]),
    .O(rst_SB_LUT4_I2_O)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0003)
  ) rst_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(\control0.state [0]),
    .I2(\control0.state [1]),
    .I3(rst),
    .O(rst_SB_LUT4_I3_O[2])
  );
  assign init_SB_LUT4_I1_O[2:1] = { \control0.state [1], \control0.state [2] };
  assign rst_SB_LUT4_I3_O[1:0] = { rst, \control0.state [2] };
  assign init_SB_LUT4_I1_O_SB_LUT4_I1_O[1:0] = \control0.done_SB_DFFE_Q_D_SB_LUT4_I3_1_O [1:0];
  assign \acc0.pp_SB_CARRY_I1_CO [0] = 1'h0;
  assign \control0.count_SB_CARRY_CI_CO [1:0] = { \control0.count [0], 1'h0 };
  assign \acc0.A  = { 1'h0, \lsr0.s_A  };
  assign \acc0.add  = \control0.add ;
  assign \acc0.clk  = clk;
  assign \acc0.rst  = \control0.reset ;
  assign \comp0.B  = { \rsr0.s_B [15:1], \control0.lsb_B  };
  assign \control0.clk  = clk;
  assign \control0.init  = init;
  assign \control0.rst  = rst;
  assign done = \control0.done ;
  assign \lsr0.clk  = clk;
  assign \lsr0.in_A  = A;
  assign \lsr0.load  = \control0.reset ;
  assign \lsr0.shift  = \control0.sh ;
  assign pp = \acc0.pp ;
  assign \rsr0.clk  = clk;
  assign \rsr0.in_B  = B;
  assign \rsr0.load  = \control0.reset ;
  assign \rsr0.s_B [0] = \control0.lsb_B ;
  assign \rsr0.shift  = \control0.sh ;
  assign w_A = { 1'h0, \lsr0.s_A  };
  assign w_B = { \rsr0.s_B [15:1], \control0.lsb_B  };
  assign w_add = \control0.add ;
  assign w_reset = \control0.reset ;
  assign w_sh = \control0.sh ;
endmodule
